-- ta, tb
/*DROP TABLE IF EXISTS AuBook;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS Publ;

CREATE TABLE Author (
    AuId varchar(9) PRIMARY KEY,
    AuthName VARCHAR(20) NOT NULL,
    born DATE,
    died DATE,
    CONSTRAINT born_check CHECK (born <= died)
);

CREATE TABLE Publ (
    pubid VARCHAR(20),
    pubname VARCHAR(20) UNIQUE,
    address VARCHAR(50) DEFAULT 'unknown',
    PRIMARY KEY(pubid)
);

CREATE TABLE Books (
    ISBN VARCHAR(20) PRIMARY KEY,
    title VARCHAR(20) UNIQUE,
    pages INTEGER CONSTRAINT check_pages CHECK (pages > 0),
    pubid VARCHAR(20),
    price NUMERIC(6, 3) CONSTRAINT check_price CHECK (price > 0),
    FOREIGN KEY(pubid) REFERENCES Publ(pubid)
);

CREATE TABLE AuBook (
    Auid VARCHAR(9),
    ISBN VARCHAR(20),
    PRIMARY KEY(Auid),
    FOREIGN KEY(ISBN) REFERENCES Books(ISBN)
);*/

-- t2
/*DROP TABLE IF EXISTS Product;*/
/*CREATE TABLE Product (
    Maker VARCHAR(1),
    Model INTEGER PRIMARY KEY,
    Type VARCHAR(7)
);

INSERT INTO Product VALUES ('A', 1001, 'PC');
INSERT INTO Product VALUES ('A', 1002, 'PC');
INSERT INTO Product VALUES ('A', 1003, 'PC');
INSERT INTO Product VALUES ('A', 2004, 'LAPTOP');
INSERT INTO Product VALUES ('A', 2005, 'LAPTOP');
INSERT INTO Product VALUES ('A', 2006, 'LAPTOP');
INSERT INTO Product VALUES ('B', 1004, 'PC');
INSERT INTO Product VALUES ('B', 1005, 'PC');
INSERT INTO Product VALUES ('B', 1006, 'PC');
INSERT INTO Product VALUES ('B', 2001, 'LAPTOP');
INSERT INTO Product VALUES ('B', 2002, 'LAPTOP');
INSERT INTO Product VALUES ('B', 2003, 'LAPTOP');
INSERT INTO Product VALUES ('C', 1007, 'PC');
INSERT INTO Product VALUES ('C', 1008, 'PC');
INSERT INTO Product VALUES ('C', 2008, 'LAPTOP');
INSERT INTO Product VALUES ('C', 2009, 'LAPTOP');
INSERT INTO Product VALUES ('C', 3002, 'PRINTER');
INSERT INTO Product VALUES ('C', 3003, 'PRINTER');
INSERT INTO Product VALUES ('C', 3006, 'PRINTER');
INSERT INTO Product VALUES ('D', 1009, 'PC');
INSERT INTO Product VALUES ('D', 1010, 'PC');
INSERT INTO Product VALUES ('D', 1011, 'PC');
INSERT INTO Product VALUES ('D', 2007, 'LAPTOP');
INSERT INTO Product VALUES ('E', 1012, 'PC');
INSERT INTO Product VALUES ('E', 1013, 'PC');
INSERT INTO Product VALUES ('E', 2010, 'LAPTOP');
INSERT INTO Product VALUES ('F', 3001, 'PRINTER');
INSERT INTO Product VALUES ('F', 3004, 'PRINTER');
INSERT INTO Product VALUES ('G', 3005, 'PRINTER');
INSERT INTO Product VALUES ('H', 3007, 'PRINTER');*/

/*ALTER TABLE product
ALTER COLUMN type TYPE VARCHAR(20) USING type::VARCHAR(20),
ADD CONSTRAINT type_check CHECK (type IN ('PC', 'LAPTOP', 'PRINTER'));*/

-- t3
/*ALTER TABLE PC ADD CONSTRAINT priec_check CHECK(speed >= 1200 or(speed < 1200 and price<=1500));*/

-- t4
/*ALTER TABLE PC ADD CONSTRAINT priec_check CHECK(speed >= 1200 or(speed < 1200 and price<=1500));*/
